apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zipkin
  namespace: {{ .Values.global.namespace | default "my-bank-app" }}
  labels:
    app: zipkin
spec:
  replicas: {{ .Values.zipkin.replicaCount }}
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: "{{ .Values.global.imagePullPolicy | default "IfNotPresent" }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 9411
              name: http
          resources:
            requests:
              memory: {{ .Values.zipkin.resources.requests.memory }}
              cpu: {{ .Values.zipkin.resources.requests.cpu }}
            limits:
              memory: {{ .Values.zipkin.resources.limits.memory }}
              cpu: {{ .Values.zipkin.resources.limits.cpu }}
