server:
  port: 8080

gateway:
  url: http://localhost:8081   # адрес Gateway API

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: front-client
            client-secret: your-client-secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/myrealm   # URL Keycloak

  thymeleaf:
    cache: false

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  observations:
    keyvalues:
      service.name: front
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true

zipkin:
  base-url: http://zipkin:9411