apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cash
  namespace: {{ .Release.Namespace }}
  labels:
    app: cash
spec:
  type: {{ .Values.cash.service.type }}
  ports:
    - port: {{ .Values.cash.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: cash
