apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace | default "my-bank-app" }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana
