apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: gateway
