server:
  port: 8083

spring:
  application:
    name: cash-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/myrealm   # Keycloak
      client:
        registration:
          cash-client:
            client-id: cash-client
            client-secret: your-client-secret
            authorization-grant-type: client_credentials
            scope: internal
        provider:
          cash-client:
            token-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token

account:
  service:
    url: http://localhost:8081

notification:
  service:
    url: http://localhost:8081

logging:
  level:
    org.springframework.security: DEBUG