server:
  port: 8083

spring:
  application:
    name: cash-service

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/myrealm   # Keycloak
      client:
        registration:
          cash-client:
            client-id: cash-client
            client-secret: your-client-secret
            authorization-grant-type: client_credentials
            scope: internal
        provider:
          cash-client:
            token-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token

account:
  service:
    url: http://localhost:8081

notification:
  service:
    url: http://localhost:8081

logging:
  level:
    org.springframework.security: DEBUG
    org.apache.kafka: DEBUG