apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app: notifications
spec:
  replicas: {{ .Values.notifications.replicaCount }}
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: "my-bank-app/notifications:latest"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8085
          resources:
            {{- toYaml .Values.notifications.resources | nindent 12 }}
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://{{ .Release.Name }}-keycloak:8080/realms/myrealm
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Release.Name }}-kafka:9092"
