apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications
  namespace: {{ .Release.Namespace }}
  labels:
    app: notifications
spec:
  type: {{ .Values.notifications.service.type }}
  ports:
    - port: {{ .Values.notifications.service.port }}
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: notifications
