apiVersion: v2
name: my-bank-app
description: Zonchik Helm-chart for My Bank Application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: 1.0.0
    repository: file://./kafka
    condition: kafka.enabled
  - name: accounts
    version: 1.0.0
    repository: file://./accounts
    condition: accounts.enabled
  - name: cash
    version: 1.0.0
    repository: file://./cash
    condition: cash.enabled
  - name: transfer
    version: 1.0.0
    repository: file://./transfer
    condition: transfer.enabled
  - name: notifications
    version: 1.0.0
    repository: file://./notifications
    condition: notifications.enabled
  - name: gateway
    version: 1.0.0
    repository: file://./gateway
    condition: gateway.enabled
  - name: front
    version: 1.0.0
    repository: file://./front
    condition: front.enabled
  - name: keycloak
    version: 24.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: global.keycloak.enabled
