apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transfer
  namespace: {{ .Values.global.namespace }}
  labels:
    app: transfer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: transfer
